name: Build and Deploy on Tag

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login https://registry.booknote.site -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        cd booknote
        docker build . \
          --build-arg DB_URL=${{ secrets.DB_URL }} \
          --build-arg DB_USER_NAME=${{ secrets.DB_USER_NAME }} \
          --build-arg DB_PASS_WORD=${{ secrets.DB_PASS_WORD }} \
          --build-arg REDIS_HOST=${{ secrets.REDIS_HOST }} \
          --build-arg REDIS_PORT=${{ secrets.REDIS_PORT }} \
          --build-arg KAFKA_HOST=${{ secrets.KAFKA_HOST }} \
          --build-arg NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
          --build-arg NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
          -t registry.booknote.site/booknote-backend:latest

    - name: Push Docker image
      run: docker push registry.booknote.site/booknote-backend:latest

    - name: Send POST request to webhook
      run: |
        curl -X POST https://webhook.booknote.site \
        -H "Content-Type: application/json" \
        -d '{"status": "success", "message": "Deployment completed for tag ${{ github.ref_name }}", "authKey": "${{ secrets.WEBHOOK_AUTH_KEY }}", "serviceName": "BooknoteBackend"}'

    - name: Logout from Docker registry
      run: docker logout registry.booknote.site
